json.id user.id
json.first_name user.first_name
json.last_name user.last_name
json.email user.email
json.phone user.phone
json.age user.age
json.username user.username
json.facebook_user_id user.facebook_user_id
json.google_user_id user.google_user_id
json.token user.token
json.gender user.gender
json.lat user.lat
json.lng user.lng
json.bio user.bio
json.photo_url user.photo_url