# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: notice #log levels: log, notice, warning, error, fatal, and panic
  pool: 5
  host: localhost

development:
  <<: *default
  # host: <%= Rails.application.secrets.database['host'] %>
  username: postgres #<%= Rails.application.secrets.database['username'] %>
  password: postgres #<%= Rails.application.secrets.database['password'] %>
  database: ghardekhoo_development

production:
  <<: *default 
  host: <%= Rails.application.secrets.database['host'] %>
  username: <%= Rails.application.secrets.database['username'] %>
  password: <%= Rails.application.secrets.database['password'] %>
  database: <%= Rails.application.secrets.database['name'] %> 

